export const ZharChallengesAddress = '0x587780d5dE651caA519285AF9D12BC099615Fc3d';
export const ZharChallengesABI = [
  {
    inputs: [
      { internalType: 'address', name: '_fireXPToken', type: 'address' },
      { internalType: 'address', name: '_europToken', type: 'address' },
      { internalType: 'address', name: '_defiTreasury', type: 'address' },
      { internalType: 'address', name: '_owner', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'EnforcedPause', type: 'error' },
  { inputs: [], name: 'ExpectedPause', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'OwnableInvalidOwner',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  { inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'challengeId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'zharriorReward', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'igniterReward', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'protocolReward', type: 'uint256' },
    ],
    name: 'ChallengeCompleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'challengeId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'igniter', type: 'address' },
      { indexed: true, internalType: 'address', name: 'forCreator', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'expiration', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'disputePeriod', type: 'uint256' },
      { indexed: false, internalType: 'string', name: 'description', type: 'string' },
      { indexed: false, internalType: 'uint256', name: 'challengeCreatorReward', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'treasury', type: 'uint256' },
    ],
    name: 'ChallengeCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'challengeId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'stoker', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'ChallengeDepositIncrease',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint256', name: 'challengeId', type: 'uint256' }],
    name: 'ChallengeExpired',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'challengeId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'totalDisputeValue', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'treasuryValue', type: 'uint256' },
    ],
    name: 'ChallengeFailed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'creator', type: 'address' },
      { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      { indexed: false, internalType: 'string', name: 'metadataUri', type: 'string' },
    ],
    name: 'CreatorRegistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'FireXPAwarded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
    name: 'Paused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'challengeId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'disputer', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'disputeValue', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'totalDisputeValue', type: 'uint256' },
    ],
    name: 'ProofDisputed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'challengeId', type: 'uint256' },
      { indexed: false, internalType: 'string', name: 'proofUri', type: 'string' },
    ],
    name: 'ProofSubmitted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
    name: 'Unpaused',
    type: 'event',
  },
  {
    inputs: [],
    name: 'DEFI_SHARE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'DISPUTE_THRESHOLD',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_IGNITER_CAP',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_IGNITER_SHARE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ZHARRIOR_SHARE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_challengeId', type: 'uint256' },
      { internalType: 'address', name: '_user', type: 'address' },
    ],
    name: 'canUserDispute',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'challengeCounter',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'challenges',
    outputs: [
      { internalType: 'uint256', name: 'challengeId', type: 'uint256' },
      { internalType: 'address', name: 'forCreator', type: 'address' },
      { internalType: 'address', name: 'igniter', type: 'address' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'treasury', type: 'uint256' },
      { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
      { internalType: 'uint256', name: 'expiration', type: 'uint256' },
      { internalType: 'uint256', name: 'challengeCreatorReward', type: 'uint256' },
      { internalType: 'string', name: 'proofUri', type: 'string' },
      { internalType: 'uint256', name: 'proofUpdatedAt', type: 'uint256' },
      { internalType: 'uint256', name: 'claimedAt', type: 'uint256' },
      { internalType: 'uint256', name: 'disputePeriod', type: 'uint256' },
      { internalType: 'enum ZharChallenges.ChallengeStatus', name: 'status', type: 'uint8' },
      { internalType: 'uint256', name: 'totalDisputeValue', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_challengeId', type: 'uint256' }],
    name: 'claimRefund',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_challengeId', type: 'uint256' }],
    name: 'claimReward',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_forCreator', type: 'address' },
      { internalType: 'string', name: '_description', type: 'string' },
      { internalType: 'uint256', name: '_expiration', type: 'uint256' },
      { internalType: 'uint256', name: '_challengeCreatorReward', type: 'uint256' },
      { internalType: 'uint256', name: '_disputePeriod', type: 'uint256' },
      { internalType: 'uint256', name: '_initialStake', type: 'uint256' },
    ],
    name: 'createChallenge',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'creators',
    outputs: [
      { internalType: 'address', name: 'creator', type: 'address' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'metadataUri', type: 'string' },
      { internalType: 'bool', name: 'isActive', type: 'bool' },
      { internalType: 'uint256', name: 'totalChallengesCompleted', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'defiTreasury',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_challengeId', type: 'uint256' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'depositToChallenge',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_challengeId', type: 'uint256' }],
    name: 'disputeProof',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_token', type: 'address' },
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'emergencyWithdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'europToken',
    outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'fireXPToken',
    outputs: [{ internalType: 'contract IFireXp', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_challengeId', type: 'uint256' }],
    name: 'getChallengeDisputers',
    outputs: [
      { internalType: 'address[]', name: '', type: 'address[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_challengeId', type: 'uint256' }],
    name: 'getChallengeStakers',
    outputs: [
      { internalType: 'address[]', name: '', type: 'address[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_challengeId', type: 'uint256' }],
    name: 'getDisputeStatus',
    outputs: [
      { internalType: 'uint256', name: 'totalDisputeValue', type: 'uint256' },
      { internalType: 'uint256', name: 'totalTreasury', type: 'uint256' },
      { internalType: 'uint256', name: 'disputePercentage', type: 'uint256' },
      { internalType: 'bool', name: 'thresholdReached', type: 'bool' },
      { internalType: 'uint256', name: 'timeLeft', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getUserChallenges',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'pause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_name', type: 'string' },
      { internalType: 'string', name: '_metadataUri', type: 'string' },
    ],
    name: 'registerCreator',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newTreasury', type: 'address' }],
    name: 'setDefiTreasury',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_challengeId', type: 'uint256' },
      { internalType: 'string', name: '_proofUri', type: 'string' },
    ],
    name: 'submitProof',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'unpause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'userChallenges',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
