export const ZharChallengesAddress = '0x5f83c882b6e5e6fb1d8445ac9346100f27b5bab9' as const;
export const ZharChallengesABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_fireXPToken', type: 'address', internalType: 'address' },
      { name: '_europToken', type: 'address', internalType: 'address' },
      { name: '_defiTreasury', type: 'address', internalType: 'address' },
      { name: '_owner', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'DEFI_SHARE',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DISPUTE_THRESHOLD',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_IGNITER_CAP',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_IGNITER_SHARE',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ZHARRIOR_SHARE',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'canUserDispute',
    inputs: [
      { name: '_challengeId', type: 'uint256', internalType: 'uint256' },
      { name: '_user', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'challengeCounter',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'challenges',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'challengeId', type: 'uint256', internalType: 'uint256' },
      { name: 'forCreator', type: 'address', internalType: 'address' },
      { name: 'igniter', type: 'address', internalType: 'address' },
      { name: 'description', type: 'string', internalType: 'string' },
      { name: 'treasury', type: 'uint256', internalType: 'uint256' },
      { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
      { name: 'expiration', type: 'uint256', internalType: 'uint256' },
      { name: 'challengeCreatorReward', type: 'uint256', internalType: 'uint256' },
      { name: 'proofUri', type: 'string', internalType: 'string' },
      { name: 'proofUpdatedAt', type: 'uint256', internalType: 'uint256' },
      { name: 'claimedAt', type: 'uint256', internalType: 'uint256' },
      { name: 'disputePeriod', type: 'uint256', internalType: 'uint256' },
      { name: 'status', type: 'uint8', internalType: 'enum ZharChallenges.ChallengeStatus' },
      { name: 'totalDisputeValue', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'claimRefund',
    inputs: [{ name: '_challengeId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimReward',
    inputs: [{ name: '_challengeId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createChallenge',
    inputs: [
      { name: '_forCreator', type: 'address', internalType: 'address' },
      { name: '_description', type: 'string', internalType: 'string' },
      { name: '_expiration', type: 'uint256', internalType: 'uint256' },
      { name: '_challengeCreatorReward', type: 'uint256', internalType: 'uint256' },
      { name: '_disputePeriod', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'creators',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [
      { name: 'creator', type: 'address', internalType: 'address' },
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'metadataUri', type: 'string', internalType: 'string' },
      { name: 'isActive', type: 'bool', internalType: 'bool' },
      { name: 'totalChallengesCompleted', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'defiTreasury',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'depositToChallenge',
    inputs: [
      { name: '_challengeId', type: 'uint256', internalType: 'uint256' },
      { name: '_amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'disputeProof',
    inputs: [{ name: '_challengeId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'emergencyWithdraw',
    inputs: [
      { name: '_token', type: 'address', internalType: 'address' },
      { name: '_to', type: 'address', internalType: 'address' },
      { name: '_amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'europToken',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'fireXPToken',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IFireXp' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getChallengeDisputers',
    inputs: [{ name: '_challengeId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: '', type: 'address[]', internalType: 'address[]' },
      { name: '', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getChallengeStakers',
    inputs: [{ name: '_challengeId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: '', type: 'address[]', internalType: 'address[]' },
      { name: '', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getDisputeStatus',
    inputs: [{ name: '_challengeId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'totalDisputeValue', type: 'uint256', internalType: 'uint256' },
      { name: 'totalTreasury', type: 'uint256', internalType: 'uint256' },
      { name: 'disputePercentage', type: 'uint256', internalType: 'uint256' },
      { name: 'thresholdReached', type: 'bool', internalType: 'bool' },
      { name: 'timeLeft', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserChallenges',
    inputs: [{ name: '_user', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'pause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'registerCreator',
    inputs: [
      { name: '_name', type: 'string', internalType: 'string' },
      { name: '_metadataUri', type: 'string', internalType: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setDefiTreasury',
    inputs: [{ name: '_newTreasury', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'submitProof',
    inputs: [
      { name: '_challengeId', type: 'uint256', internalType: 'uint256' },
      { name: '_proofUri', type: 'string', internalType: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  { type: 'function', name: 'unpause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'userChallenges',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ChallengeCompleted',
    inputs: [
      { name: 'challengeId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'zharriorReward', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'igniterReward', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'protocolReward', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChallengeCreated',
    inputs: [
      { name: 'challengeId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'igniter', type: 'address', indexed: true, internalType: 'address' },
      { name: 'forCreator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'expiration', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'disputePeriod', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'description', type: 'string', indexed: false, internalType: 'string' },
      { name: 'challengeCreatorReward', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChallengeDepositIncrease',
    inputs: [
      { name: 'challengeId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'stoker', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChallengeExpired',
    inputs: [{ name: 'challengeId', type: 'uint256', indexed: true, internalType: 'uint256' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChallengeFailed',
    inputs: [
      { name: 'challengeId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'totalDisputeValue', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'treasuryValue', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CreatorRegistered',
    inputs: [
      { name: 'creator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'name', type: 'string', indexed: false, internalType: 'string' },
      { name: 'metadataUri', type: 'string', indexed: false, internalType: 'string' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FireXPAwarded',
    inputs: [
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Paused',
    inputs: [{ name: 'account', type: 'address', indexed: false, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProofDisputed',
    inputs: [
      { name: 'challengeId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'disputer', type: 'address', indexed: true, internalType: 'address' },
      { name: 'disputeValue', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'totalDisputeValue', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProofSubmitted',
    inputs: [
      { name: 'challengeId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'proofUri', type: 'string', indexed: false, internalType: 'string' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Unpaused',
    inputs: [{ name: 'account', type: 'address', indexed: false, internalType: 'address' }],
    anonymous: false,
  },
  { type: 'error', name: 'EnforcedPause', inputs: [] },
  { type: 'error', name: 'ExpectedPause', inputs: [] },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
] as const;
